import { Product, Supplier, Category, Purchase, Sale, Expense, StockMovement, Settings } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Katana Keychains', slug: 'katana-keychains', description: 'Miniature metal katana replica keychains with scabbards' },
  { id: 'cat-2', name: 'Spinner Keychains', slug: 'spinner-keychains', description: 'Interactive dual-ring rotating anime keychains' },
  { id: 'cat-3', name: 'PVC & Rubber Keychains', slug: 'pvc-rubber-keychains', description: 'Durable soft rubber character keychains' },
  { id: 'cat-4', name: 'Acrylic Standees & Charms', slug: 'acrylic-keychains', description: 'Crystal clear acrylic anime character charms' },
  { id: 'cat-5', name: 'Collectibles & Pins', slug: 'collectibles', description: 'Enamel badges, pins, and collectible accessories' },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'DragonCraft Metalworks',
    contact_number: '+91 98765 43210',
    location: 'Surat, Gujarat',
    notes: 'Primary supplier for zinc-alloy metal Katana & Spinner keychains. Reliable quality.',
    products_supplied_count: 3,
    total_purchased_amount: 14200,
    total_purchases_count: 2,
    last_purchase_date: '2026-08-01',
  },
  {
    id: 'sup-2',
    name: 'Nippon PVC & Mold Ltd',
    contact_number: '+91 98123 98765',
    location: 'Mumbai, Maharashtra',
    notes: 'Supplier for custom molded soft rubber and PVC character keychains.',
    products_supplied_count: 2,
    total_purchased_amount: 6800,
    total_purchases_count: 1,
    last_purchase_date: '2026-07-20',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Zoro Spinner Keychain',
    sku: 'ARO-ZOR-SPN-01',
    category_id: 'cat-2',
    category_name: 'Spinner Keychains',
    subcategory: 'One Piece Collectibles',
    description: '360-degree smooth bearing spinner keychain featuring Roronoa Zoro Jolly Roger & katana motifs. High polish zinc alloy finish.',
    brand: 'Aroza Collectibles',
    tags: ['One Piece', 'Zoro', 'Spinner', 'Metal', 'Bestseller'],
    supplier_id: 'sup-1',
    supplier_name: 'DragonCraft Metalworks',
    purchase_price_default: 45,
    selling_price_default: 199,
    instagram_price: 199,
    meesho_price: 229,
    direct_price: 180,
    other_platform_price: 199,
    min_reorder_level: 10,
    current_stock: 32,
    damaged_qty: 1,
    returned_qty: 0,
    images: [
      {
        id: 'img-1-1',
        product_id: 'prod-1',
        image_url: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&auto=format&fit=crop&q=80',
        is_main: true,
        display_order: 0,
      },
      {
        id: 'img-1-2',
        product_id: 'prod-1',
        image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
        is_main: false,
        display_order: 1,
      },
    ],
    created_at: '2026-07-15T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Shusui Katana Keychain',
    sku: 'ARO-SHU-KAT-02',
    category_id: 'cat-1',
    category_name: 'Katana Keychains',
    subcategory: 'Mini Replica Katana',
    description: '22cm detailed zinc alloy black blade Shusui katana keychain with functional sheath & display stand capability.',
    brand: 'Aroza Collectibles',
    tags: ['One Piece', 'Katana', 'Shusui', 'Sword', 'Metal'],
    supplier_id: 'sup-1',
    supplier_name: 'DragonCraft Metalworks',
    purchase_price_default: 65,
    selling_price_default: 299,
    instagram_price: 299,
    meesho_price: 349,
    direct_price: 270,
    other_platform_price: 299,
    min_reorder_level: 8,
    current_stock: 14,
    damaged_qty: 0,
    returned_qty: 1,
    images: [
      {
        id: 'img-2-1',
        product_id: 'prod-2',
        image_url: 'https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=600&auto=format&fit=crop&q=80',
        is_main: true,
        display_order: 0,
      },
    ],
    created_at: '2026-07-16T11:30:00Z',
  },
  {
    id: 'prod-3',
    name: 'Enma Katana Keychain',
    sku: 'ARO-ENM-KAT-03',
    category_id: 'cat-1',
    category_name: 'Katana Keychains',
    subcategory: 'Mini Replica Katana',
    description: 'Purple floral pattern guard Enma replica katana keychain. Crafted with premium heavy metal sheath.',
    brand: 'Aroza Collectibles',
    tags: ['One Piece', 'Enma', 'Katana', 'Wano', 'Purple'],
    supplier_id: 'sup-1',
    supplier_name: 'DragonCraft Metalworks',
    purchase_price_default: 68,
    selling_price_default: 319,
    instagram_price: 319,
    meesho_price: 369,
    direct_price: 290,
    other_platform_price: 319,
    min_reorder_level: 5,
    current_stock: 4, // Low stock indicator!
    damaged_qty: 0,
    returned_qty: 0,
    images: [
      {
        id: 'img-3-1',
        product_id: 'prod-3',
        image_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        is_main: true,
        display_order: 0,
      },
    ],
    created_at: '2026-07-18T14:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Kuina Wado Ichimonji Keychain',
    sku: 'ARO-KUI-WAD-04',
    category_id: 'cat-1',
    category_name: 'Katana Keychains',
    subcategory: 'Mini Replica Katana',
    description: 'Pure white sheath Wado Ichimonji katana keychain. Classic collectible tribute item.',
    brand: 'Aroza Collectibles',
    tags: ['Kuina', 'Wado Ichimonji', 'Katana', 'One Piece'],
    supplier_id: 'sup-1',
    supplier_name: 'DragonCraft Metalworks',
    purchase_price_default: 60,
    selling_price_default: 279,
    instagram_price: 279,
    meesho_price: 319,
    direct_price: 250,
    other_platform_price: 279,
    min_reorder_level: 5,
    current_stock: 18,
    damaged_qty: 0,
    returned_qty: 0,
    images: [
      {
        id: 'img-4-1',
        product_id: 'prod-4',
        image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        is_main: true,
        display_order: 0,
      },
    ],
    created_at: '2026-07-20T09:15:00Z',
  },
  {
    id: 'prod-5',
    name: 'Anime Rubber Chibi Keychain',
    sku: 'ARO-CHB-PVC-05',
    category_id: 'cat-3',
    category_name: 'PVC & Rubber Keychains',
    subcategory: 'Chibi Anime Figures',
    description: 'Double-sided soft flexible PVC rubber keychain with vibrant fade-resistant colors.',
    brand: 'Aroza Collectibles',
    tags: ['Chibi', 'Rubber', 'PVC', 'Anime', 'Lightweight'],
    supplier_id: 'sup-2',
    supplier_name: 'Nippon PVC & Mold Ltd',
    purchase_price_default: 25,
    selling_price_default: 149,
    instagram_price: 149,
    meesho_price: 169,
    direct_price: 130,
    other_platform_price: 149,
    min_reorder_level: 15,
    current_stock: 45,
    damaged_qty: 2,
    returned_qty: 0,
    images: [
      {
        id: 'img-5-1',
        product_id: 'prod-5',
        image_url: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
        is_main: true,
        display_order: 0,
      },
    ],
    created_at: '2026-07-22T16:45:00Z',
  },
];

export const INITIAL_PURCHASES: Purchase[] = [
  {
    id: 'pur-001',
    purchase_number: 'PUR-#001',
    supplier_id: 'sup-1',
    supplier_name: 'DragonCraft Metalworks',
    purchase_date: '2026-07-20',
    transport_cost: 250,
    packaging_cost: 150,
    other_expenses: 0,
    payment_method: 'UPI Bank Transfer',
    notes: 'First batch of Zoro Spinners & Katana replicas.',
    total_amount: 8850,
    items: [
      { product_id: 'prod-1', product_name: 'Zoro Spinner Keychain', quantity: 50, unit_cost: 45, total_cost: 2250 },
      { product_id: 'prod-2', product_name: 'Shusui Katana Keychain', quantity: 30, unit_cost: 65, total_cost: 1950 },
      { product_id: 'prod-3', product_name: 'Enma Katana Keychain', quantity: 20, unit_cost: 68, total_cost: 1360 },
      { product_id: 'prod-4', product_name: 'Kuina Wado Ichimonji Keychain', quantity: 30, unit_cost: 60, total_cost: 1800 },
    ],
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'pur-002',
    purchase_number: 'PUR-#002',
    supplier_id: 'sup-2',
    supplier_name: 'Nippon PVC & Mold Ltd',
    purchase_date: '2026-07-25',
    transport_cost: 180,
    packaging_cost: 100,
    other_expenses: 0,
    payment_method: 'GPay',
    notes: 'Initial order for Rubber Chibi PVC keychains.',
    total_amount: 2030,
    items: [
      { product_id: 'prod-5', product_name: 'Anime Rubber Chibi Keychain', quantity: 70, unit_cost: 25, total_cost: 1750 },
    ],
    created_at: '2026-07-25T14:30:00Z',
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-001',
    order_number: 'ORD-IG-1001',
    sale_date: '2026-08-02',
    platform: 'Instagram',
    customer_name: 'Rahul V.',
    shipping_charged: 60,
    shipping_cost: 50,
    platform_fee: 0,
    packaging_cost: 12,
    discount: 0,
    other_expense: 0,
    payment_status: 'Paid',
    notes: 'Direct DM order via Instagram story feature',
    total_revenue: 458, // (199 + 199 + 60)
    total_cost: 90,     // 2 x 45
    total_selling_expenses: 62, // 50 + 12
    net_profit: 306,
    profit_margin: 66.8,
    items: [
      { product_id: 'prod-1', product_name: 'Zoro Spinner Keychain', quantity: 2, unit_price: 199, unit_cost: 45 },
    ],
    created_at: '2026-08-02T11:20:00Z',
  },
  {
    id: 'sale-002',
    order_number: 'ORD-MSH-2042',
    sale_date: '2026-08-05',
    platform: 'Meesho',
    customer_name: 'Sneha Patel',
    shipping_charged: 0,
    shipping_cost: 0,
    platform_fee: 45,
    packaging_cost: 15,
    discount: 20,
    other_expense: 0,
    payment_status: 'Paid',
    notes: 'Meesho Marketplace Order',
    total_revenue: 329, // 349 - 20
    total_cost: 65,     // 1 x 65
    total_selling_expenses: 60, // 45 + 15
    net_profit: 204,
    profit_margin: 62.0,
    items: [
      { product_id: 'prod-2', product_name: 'Shusui Katana Keychain', quantity: 1, unit_price: 349, unit_cost: 65 },
    ],
    created_at: '2026-08-05T15:45:00Z',
  },
  {
    id: 'sale-003',
    order_number: 'ORD-DIR-3012',
    sale_date: '2026-08-10',
    platform: 'Direct',
    customer_name: 'Aditya Sharma',
    shipping_charged: 0,
    shipping_cost: 0,
    platform_fee: 0,
    packaging_cost: 10,
    discount: 19,
    other_expense: 0,
    payment_status: 'Paid',
    notes: 'Local meetup sale in college event',
    total_revenue: 600, // (319 + 300 - 19)
    total_cost: 133,    // 68 + 65
    total_selling_expenses: 10,
    net_profit: 457,
    profit_margin: 76.1,
    items: [
      { product_id: 'prod-3', product_name: 'Enma Katana Keychain', quantity: 1, unit_price: 319, unit_cost: 68 },
      { product_id: 'prod-2', product_name: 'Shusui Katana Keychain', quantity: 1, unit_price: 300, unit_cost: 65 },
    ],
    created_at: '2026-08-10T18:00:00Z',
  },
  {
    id: 'sale-004',
    order_number: 'ORD-WA-4050',
    sale_date: '2026-08-14',
    platform: 'WhatsApp',
    customer_name: 'Kavya S.',
    shipping_charged: 50,
    shipping_cost: 45,
    platform_fee: 0,
    packaging_cost: 10,
    discount: 0,
    other_expense: 0,
    payment_status: 'Paid',
    notes: 'WhatsApp Catalog sale',
    total_revenue: 348, // 149 + 149 + 50
    total_cost: 50,     // 2 x 25
    total_selling_expenses: 55,
    net_profit: 243,
    profit_margin: 69.8,
    items: [
      { product_id: 'prod-5', product_name: 'Anime Rubber Chibi Keychain', quantity: 2, unit_price: 149, unit_cost: 25 },
    ],
    created_at: '2026-08-14T12:10:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    date: '2026-07-28',
    category: 'Packaging',
    amount: 850,
    description: 'Custom Aroza Collectibles branded thank you cards, bubble mailers & stickers',
    created_at: '2026-07-28T11:00:00Z',
  },
  {
    id: 'exp-002',
    date: '2026-08-01',
    category: 'Marketing',
    amount: 1200,
    description: 'Instagram sponsored story ad campaign for Zoro Spinner Keychain launch',
    created_at: '2026-08-01T14:20:00Z',
  },
  {
    id: 'exp-003',
    date: '2026-08-08',
    category: 'Petrol',
    amount: 400,
    description: 'Travel to courier dispatch center & local parcel drop',
    created_at: '2026-08-08T16:00:00Z',
  },
];

export const INITIAL_MOVEMENTS: StockMovement[] = [
  {
    id: 'mov-1',
    product_id: 'prod-1',
    product_name: 'Zoro Spinner Keychain',
    movement_type: 'PURCHASE',
    reference_id: 'pur-001',
    reference_type: 'PURCHASE',
    quantity_changed: 50,
    cost_per_unit: 45,
    resulting_stock: 50,
    notes: 'Initial Stock Purchase PUR-#001',
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'mov-2',
    product_id: 'prod-1',
    product_name: 'Zoro Spinner Keychain',
    movement_type: 'SALE',
    reference_id: 'sale-001',
    reference_type: 'SALE',
    quantity_changed: -2,
    cost_per_unit: 45,
    resulting_stock: 48,
    notes: 'Sold on Instagram ORD-IG-1001',
    created_at: '2026-08-02T11:20:00Z',
  },
  {
    id: 'mov-3',
    product_id: 'prod-1',
    product_name: 'Zoro Spinner Keychain',
    movement_type: 'DAMAGED',
    quantity_changed: -1,
    cost_per_unit: 45,
    resulting_stock: 47,
    notes: 'Slight bearing scratch during quality inspection',
    created_at: '2026-08-06T09:00:00Z',
  },
];

export const INITIAL_SETTINGS: Settings = {
  business_name: 'Aroza Collectibles',
  currency: '₹',
  default_platform: 'Instagram',
  default_packaging_cost: 12.0,
  default_shipping_cost: 50.0,
  low_stock_threshold: 5,
  theme_preference: 'warm',
};
